Repository python-humanize/humanize, pull requests merged in 2022-08, with the labels that each got.

#46 Add Greek translation
  README.md
  src/humanize/locale/el_GR/LC_MESSAGES/humanize.po
Labels: changelog: Added

#47 Fix "ValueError: math domain error" for metric(0)
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Fixed

#50 Update pre-commit
  .pre-commit-config.yaml
Labels: changelog: skip, testing

#49 Internationalise intcomma for de_DE locale
  src/humanize/i18n.py
  tests/test_i18n.py
Labels: changelog: Added

#42 Fix some pylint findings
  src/humanize/filesize.py
  src/humanize/number.py
  src/humanize/time.py
  tests/test_i18n.py
  tests/test_time.py
Labels: changelog: Fixed

#52 Fix intcomma() failing with a string as input when ndigits is not None
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Fixed

#53 Internationalise the decimal separator in intcomma()
  src/humanize/__init__.py
  src/humanize/i18n.py
  src/humanize/number.py
  tests/test_i18n.py
Labels: changelog: Added
