Repository python-humanize/humanize, pull requests merged in 2022-10, with the labels that each got.

#64 Stabilize test name for tests using FakeDate
  tests/test_time.py
Labels: changelog: skip

#66 Add pt_BR separators
  src/humanize/i18n.py
  tests/test_i18n.py
Labels: changelog: Added

#63 Bug-Fix: handle NaN
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Fixed

#69 Test on 3.11 instead of 3.11-dev
  .github/workflows/test.yml
Labels: changelog: skip, testing
