Repository python-humanize/humanize, pull requests merged in 2022-04, with the labels that each got.

#2 Update repo links
  .github/CONTRIBUTING.md
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  README.md
  RELEASING.md
  mkdocs.yml
  setup.cfg
  src/humanize/locale/da_DK/LC_MESSAGES/humanize.po
  src/humanize/locale/sv_SE/LC_MESSAGES/humanize.po
Labels: changelog: Changed

#4 Add dependabot
  .github/dependabot.yml
Labels: changelog: skip

#9 Add 'dependencies' and 'release' labels
  .github/labels.yml
Labels: changelog: skip

#10 GHA: add workflow to require changelog label
  .github/workflows/require-pr-label.yml
Labels: changelog: skip

#11 Removed VERSION from __all__
  src/humanize/__init__.py
Labels: changelog: Fixed
