Repository python-humanize/humanize, pull requests merged in 2022-06, with the labels that each got.

#22 Add humanize.metric() for converting big/small numbers to SI units
  src/humanize/__init__.py
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Added

#26 Fix intcomma with ndigits=0
  src/humanize/number.py
  tests/test_number.py
Labels: bug, changelog: Fixed

#23 BUG: Use %d for year translations convert to string for intcomma after
  src/humanize/time.py
  tests/test_i18n.py
Labels: changelog: Fixed

#29 Update annotations: naturadelta and naturaltime can also accept a float
  src/humanize/filesize.py
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Fixed

#31 Update annotations, docs, and tests: naturaltime can also accept a timedelta
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Fixed
