Repository python-humanize/humanize, pull requests merged in 2023-07, with the labels that each got.

#128 Update docs link to https://humanize.readthedocs.io
  README.md
  mkdocs.yml
  pyproject.toml
Labels: changelog: Changed

#131 Add Hungarian localization
  src/humanize/i18n.py
  src/humanize/locale/hu_HU/LC_MESSAGES/humanize.po
Labels: changelog: Added

#133 Remove default 'cache-dependency-path: pyproject.toml'
  .github/workflows/test.yml
Labels: changelog: skip
