Repository python-humanize/humanize, pull requests merged in 2023-08, with the labels that each got.

#137 Docs: fix formatting of return value
  src/humanize/number.py
Labels: documentation, changelog: Fixed

#139 Revise Turkish localization
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
Labels: changelog: Added

#123 Move logic to convert aware datetime to naive into function
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Fixed

#141 Remove useless shebangs
  src/humanize/number.py
  src/humanize/time.py
Labels: changelog: Fixed
