Repository python-humanize/humanize, pull requests merged in 2023-10, with the labels that each got.

#146 Fix args for stricter Google docstring parsing by Griffe
  docs/index.md
  mkdocs.yml
  src/humanize/filesize.py
  src/humanize/number.py
Labels: documentation, changelog: skip

#150 Add Klingon translation
  README.md
  src/humanize/locale/tlh/LC_MESSAGES/humanize.po
Labels: changelog: Added

#151 Require PR label: Update permissions
  .github/workflows/require-pr-label.yml
Labels: changelog: skip

#149 Add Hebrew localization
  README.md
  src/humanize/locale/he_IL/LC_MESSAGES/humanize.po
Labels: changelog: Added

#147 Fix DeprecationWarning: Plural value must be an integer, got float
  src/humanize/time.py
Labels: changelog: Fixed
