Repository python-humanize/humanize, pull requests merged in 2023-01, with the labels that each got.

#84 Add Basque translation
  README.md
  src/humanize/locale/eu/LC_MESSAGES/humanize.po
Labels: changelog: Added

#80 Cosmetic: improve exception traceback readability
  .github/workflows/test.yml
  .pre-commit-config.yaml
  src/humanize/i18n.py
  src/humanize/number.py
  src/humanize/time.py
Labels: changelog: Changed

#89 Add localisation for thousand, fixing German plurals
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.po
Labels: changelog: Fixed

#76 Filesize simplification
  src/humanize/filesize.py
Labels: changelog: Changed

#90 Replace setup.cfg with pyproject.toml
  .flake8
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: changelog: Changed

#87 Fix intword for 1,000 decillion
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Fixed

#92 Bump isort to fix Poetry
  .pre-commit-config.yaml
Labels: changelog: skip, dependencies
