Repository python-humanize/humanize, pull requests merged in 2024-10, with the labels that each got.

#206 Fix rollover from ZB to 1.0 YB
  src/humanize/filesize.py
  tests/test_filesize.py
Labels: changelog: Fixed

#204 Fix i18n _get_default_locale_path
  src/humanize/i18n.py
  tests/test_i18n.py
Labels: changelog: Fixed

#110 Add natural_list
  .gitignore
  docs/index.md
  docs/lists.md
  mkdocs.yml
  src/humanize/__init__.py
  src/humanize/lists.py
  tests/test_lists.py
Labels: changelog: Added

#209 Adjust docs order for lists
  docs/index.md
  mkdocs.yml
Labels: documentation, changelog: skip

#212 Lint and test with tox-uv
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: changelog: Changed

#213 Release to PyPI using Trusted Publishing
  .github/workflows/release.yml
  RELEASING.md
Labels: changelog: Added
