Repository python-humanize/humanize, pull requests merged in 2024-02, with the labels that each got.

#170 Replace deprecated pydocstyle with Ruff and update to Black 2024 style
  .pre-commit-config.yaml
  pyproject.toml
  src/humanize/i18n.py
  src/humanize/number.py
  src/humanize/time.py
  tests/test_i18n.py
  tests/test_number.py
  tests/test_time.py
Labels: changelog: Changed

#172 Set COVERAGE_CORE=sysmon for faster test coverage on 3.12+
  .github/workflows/test.yml
  pyproject.toml
  tox.ini
Labels: changelog: skip, testing

#169 Fix naturaldelta sub second precision
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Fixed

#173 Fix handling of negative time deltas
  .pre-commit-config.yaml
  src/humanize/time.py
  tests/test_time.py
Labels: bug, changelog: Fixed
