Repository python-humanize/humanize, pull requests merged in 2025-02, with the labels that each got.

#232 Generate translation binaries during release
  .github/workflows/release.yml
Labels: changelog: Fixed

#230 Handle en_GB and en_US locale
  src/humanize/i18n.py
  tests/test_i18n.py
Labels: changelog: Added

#233 Update config
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: changelog: skip

#234 Defer imports for faster overall import time: 19 ms -> 5 ms
  .pre-commit-config.yaml
  docs/requirements.txt
  requirements-mypy.txt
  src/humanize/i18n.py
  src/humanize/lists.py
  src/humanize/number.py
  src/humanize/time.py
  tox.ini
Labels: changelog: Changed

#235 Add support for Python 3.14 and test PyPy3.11
  .github/workflows/require-pr-label.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .yamlfmt.yaml
  pyproject.toml
  tox.ini
Labels: changelog: Added

#236 Replace deprecated classifier with licence expression (PEP 639)
  pyproject.toml
Labels: changelog: Changed

#238 Defer imports for faster overall import time: 5 ms -> 3 ms
  src/humanize/number.py
  src/humanize/time.py
Labels: changelog: Changed

#240 Fix regression in `naturalsize` for float
  src/humanize/filesize.py
  tests/test_filesize.py
Labels: changelog: Fixed
